# Generated by Django 4.1.7 on 2023-03-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder1', '0002_persona_estudiante_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='numero',
            new_name='idc',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='name',
        ),
    ]
